package main.system;

public enum GuiEventType {
    GRID_CREATED,
    CREATE_RADIAL_MENU,
    SHOW_PHASE_ANIM,
    SHOW_GREEN_BORDER,
    SHOW_RED_BORDER,
    SHOW_BLUE_BORDERS,
    SELECT_MULTI_OBJECTS,
    INGAME_EVENT_TRIGGERED,
    ACTIVE_UNIT_SELECTED,
    @Deprecated
    CELL_UPDATE,
    SHOW_TOOLTIP,
    CREATE_UNITS_MODEL
}
